version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
   - pdf
   - epub

python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .
